version: '3.8'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./conf/php/Dockerfile
    image: kurtay/php
    volumes:
      - ./app:/app
    env_file:
      - .env

  composer:
    image: composer
    container_name: composer
    volumes:
      - "./app:/app"
    command: install
    depends_on:
      - php

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./conf/nginx/Dockerfile
    image: kurtay/nginx
    ports:
      - '8080:8080'
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php